- name: store sha256 hash of ssh key for user {{ username }}
  shell: ssh-keygen -lf <(echo "{{ ssh_key }}") | awk '{print $2}'
  no_log: true
  args:
    executable: /bin/bash
  changed_when: false
  register: sha256

- ansible.builtin.debug:
   msg: "Der ssh key ist {{ ssh_key }}, der user ist {{ username }}"
- name: dokku ssh-keys:add for user {{ username }}
  shell: "{{ 'docker exec dokku' if dokku_docker_install else '' }} dokku ssh-keys:add {{ username }} {{ ssh_key }}"
  no_log: true
  when: force_add or ssh_key_list.find(sha256.stdout) == -1 
  changed_when: true
